# Generated by Django 5.1.3 on 2024-11-10 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["-pub_date"]},
        ),
    ]
